[package]
name = "squad-layer-rotator"
version = "0.2.0"
edition = "2021"

[dependencies]
dotenv = "0.15"
chrono = "0.4"
tokio = { version = "1", features = ["full"] }
ssh2 = "0.9"
glob = "0.3"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"